### ISSUE TITLE
adventure log issues

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/WebFE#60]
Sometimes the adventure log stops updating, though events are still happening according to the statistics page and you can still see your character getting experience on the bar and the misc. box shows that the character is still moving around the map.

After viewing another in-game tab and coming back to the player tab, the adventure log sometimes loads backwards: http://puu.sh/eqffZ/a8f7e78aba.png

**Comment by seiyria** [comment]
as for the adventure log reversing, it should not be reversed client side, and it should instead be handled when appending to the adventure log instead.
