### ISSUE TITLE
Guild member information not properly loading

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/WebFE#71]
http://puu.sh/fY6dF/32d85f787b.png

http://puu.sh/fY6tx/3bb2bb2a4a.png

Some player profiles never load, leaving them as profile unknown. Some players do not update after leveling, such as Jias who is level 94 but only shows up as 82 in webFE.

**Comment by seiyria** [comment]
moved here: https://github.com/IdleLands/IdleLands/issues/847
