### ISSUE TITLE
No AttemptEnchant options on enchantress

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/WebFE#96]
Noticed this while my character was in the guild hall map. Enchantress is level 25, but [all equipment is too unsafe](http://puu.sh/glEIH/a27259ca63.png) and when clicking the drop down menu for AttemptEnchant no options are there (and I believe it should have yes and no options).

The only thing I could think would be that your character would need to be on the enchantress tile to change this, or it's bugged. If it requires being on the tile, then that's a very short window of time to make the change.

**Comment by seiyria** [comment]
In fact, all Yes/No options appear to be broken (see: Academy).

Not sure what's up but I'll take a look at it tonight.

**Comment by seiyria** [comment]
Also, an enchant is only "safe" if you're 20 levels higher than the required enchantment level. ie, +1 is only "safe" at level 30. At level 10, it has a 0% chance of happening, level 15, 25%... up to level 30, where it's 100% successful.
